name = "cosmo-note"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cosmo_note_db"
database_id = "2ccb76ba-8b20-405c-b60a-a21edc8893d5"
